package main

import (
	"fmt"
	"strings"
)

type NodeStoringImplicitDepLoader struct {
	*ImplicitDepLoader
	dep_nodes_output_ *[]*Node
}

func NewNodeStoringImplicitDepLoader(state *State,
	deps_log *DepsLog, disk_interface FileSystem,
	depfile_parser_options *DepfileParserOptions,
	explanations *Explanations,
	dep_nodes_output *[]*Node) *NodeStoringImplicitDepLoader {
	n := &NodeStoringImplicitDepLoader{}
	n.ImplicitDepLoader = NewImplicitDepLoader(state, deps_log, disk_interface, depfile_parser_options, explanations)
	n.dep_nodes_output_ = dep_nodes_output
	return n
}

func (n *NodeStoringImplicitDepLoader) ProcessDepfileDeps(edge *Edge, depfile_ins []string, err *string) bool {
	for i := 0; i < len(depfile_ins); i++ {
		var slash_bits uint64
		CanonicalizePathString(&depfile_ins[i], &slash_bits)
		node := n.state_.GetNode(depfile_ins[i], slash_bits)
		*n.dep_nodes_output_ = append(*n.dep_nodes_output_, node)
	}
	return true
}

func (l *NodeStoringImplicitDepLoader) LoadDepFile(edge *Edge, path string, err *string) bool {
	// METRIC_RECORD("depfile load") - ignored

	// Read depfile content. Treat a missing depfile as empty.
	var content string
	status := l.disk_interface_.ReadFile(path, &content, err)
	if status == StatusNotFound {
		*err = "" // clear error
	} else if status == StatusOtherError {
		*err = "loading '" + path + "': " + *err
		return false
	}

	firstOutput := edge.outputs_[0]
	if content == "" {
		l.explanations_.Record(firstOutput, "depfile '%s' is missing", path)
		return false
	}

	depfileParser := NewDepfileParser(l.depfile_parser_options_)
	depfileErr := ""
	if !depfileParser.Parse(content, &depfileErr) {
		*err = path + ": " + depfileErr
		return false
	}

	if len(depfileParser.Outs) == 0 {
		*err = path + ": no outputs declared"
		return false
	}

	// Canonicalize the primary output path.
	primaryOut := depfileParser.Outs[0]
	primaryOutLen := len(primaryOut)
	var canonicalized []byte
	var unused uint64
	CanonicalizePathBytes(canonicalized, &primaryOutLen, &unused)
	// Update the string slice (depfileParser.outs is a slice of strings, we need to replace)
	depfileParser.Outs[0] = string(canonicalized)

	// Check that this depfile matches the edge_'s output.
	if firstOutput.path_ != string(canonicalized) {
		l.explanations_.Record(firstOutput,
			"expected depfile '%s' to mention '%s', got '%s'",
			path, firstOutput.path_, string(canonicalized))
		return false
	}

	// Ensure that all mentioned outputs are outputs of the edge_.
	for _, o := range depfileParser.Outs {
		found := false
		for _, edgeOut := range edge.outputs_ {
			if edgeOut.path_ == o {
				found = true
				break
			}
		}
		if !found {
			*err = path + ": depfile mentions '" + o + "' as an output, but no such output was declared"
			return false
		}
	}

	return l.ProcessDepfileDeps(edge, depfileParser.Ins, err)
}

// Delegate 接口，用于处理发现的缺失依赖。
type MissingDependencyScannerDelegate interface {
	OnMissingDep(node *Node, path string, generator *Rule)
}

// MissingDependencyPrinter 是一个简单的 MissingDependencyScannerDelegate 实现，打印缺失依赖信息。
type MissingDependencyPrinter struct{}

func NewPrinter() *MissingDependencyPrinter {
	return &MissingDependencyPrinter{}
}

func (p *MissingDependencyPrinter) OnMissingDep(node *Node, path string, generator *Rule) {
	fmt.Printf("Missing dep: %s uses %s (generated by %s)\n", node.path_, path, generator.Name)
}

// MissingDependencyScanner 扫描依赖日志，检测缺失依赖。
type MissingDependencyScanner struct {
	delegate_               MissingDependencyScannerDelegate
	deps_log_               *DepsLog
	state_                  *State
	disk_interface_         FileSystem
	seen_                   map[*Node]bool
	nodes_missing_deps_     map[*Node]bool
	generated_nodes_        map[*Node]bool
	generator_rules_        map[*Rule]bool
	missing_dep_path_count_ int
	adjacency_map_          map[*Edge]map[*Edge]bool
}

// NewMissingDependencyScanner 创建 MissingDependencyScanner 实例。
func NewMissingDependencyScanner(delegate MissingDependencyScannerDelegate, depsLog *DepsLog, state *State, disk FileSystem) *MissingDependencyScanner {
	return &MissingDependencyScanner{
		delegate_:           delegate,
		deps_log_:           depsLog,
		state_:              state,
		disk_interface_:     disk,
		seen_:               make(map[*Node]bool),
		nodes_missing_deps_: make(map[*Node]bool),
		generated_nodes_:    make(map[*Node]bool),
		generator_rules_:    make(map[*Rule]bool),
		adjacency_map_:      make(map[*Edge]map[*Edge]bool),
	}
}

// ProcessNode 递归处理节点，收集其依赖并检测缺失。
func (s *MissingDependencyScanner) ProcessNode(node *Node) {
	if node == nil {
		return
	}
	edge := node.in_edge()
	if edge == nil {
		return
	}
	if _, ok := s.seen_[node]; ok {
		return
	}
	s.seen_[node] = true

	// 递归处理输入节点
	for _, in := range edge.inputs_ {
		s.ProcessNode(in)
	}

	// 获取依赖信息（从 deps_ log 或 depfile）
	depsType := edge.GetBinding("deps")
	if depsType != "" {
		deps := s.deps_log_.GetDeps(node)
		if deps != nil {
			s.ProcessNodeDeps(node, deps.nodes)
		}
	} else {
		var parser_opts DepfileParserOptions
		var depfile_deps []*Node
		var dep_loader = NewNodeStoringImplicitDepLoader(s.state_, s.deps_log_, s.disk_interface_,
			&parser_opts, nil,
			&depfile_deps)
		var err string
		dep_loader.LoadDeps(edge, &err)
		if len(depfile_deps) != 0 {
			s.ProcessNodeDeps(node, depfile_deps)
		}
	}
}

// loadDepfileDeps 从 depfile 中读取依赖节点（不修改图的隐式依赖）。
func (s *MissingDependencyScanner) loadDepfileDeps(edge *Edge) []*Node {
	depfile := edge.GetUnescapedDepfile()
	if depfile == "" {
		return nil
	}
	// 展开 $out 等变量（简化：直接替换，实际应使用 edge_.env_）
	depfile = strings.ReplaceAll(depfile, "$out", edge.outputs_[0].path_)
	var content string
	var err string
	status := s.disk_interface_.ReadFile(depfile, &content, &err)
	if status != StatusOkay {
		return nil
	}
	parser := NewDepfileParser(&DepfileParserOptions{})
	if !parser.Parse(content, &err) {
		return nil
	}
	var nodes []*Node
	for _, in := range parser.Ins {
		var slashBits uint64
		CanonicalizePathString(&in, &slashBits)
		node := s.state_.GetNode(in, 0)
		nodes = append(nodes, node)
	}
	return nodes
}

// processNodeDeps 处理给定节点的依赖节点列表，检测是否有缺失路径。
func (s *MissingDependencyScanner) ProcessNodeDeps(node *Node, depNodes []*Node) {
	edge := node.in_edge()
	// 收集所有依赖边的集合
	depEdges := make(map[*Edge]bool)
	for _, dn := range depNodes {
		// 特殊例外：依赖 build.ninja 不算缺失（因为它由配置工具生成）
		if dn.path_ == "build.ninja" {
			continue
		}
		if de := dn.in_edge(); de != nil {
			depEdges[de] = true
		}
	}
	var missingEdges []*Edge
	for de := range depEdges {
		if !s.PathExistsBetween(de, edge) {
			missingEdges = append(missingEdges, de)
		}
	}
	if len(missingEdges) == 0 {
		return
	}
	// 记录缺失信息
	ruleNames := make(map[string]bool)
	for _, me := range missingEdges {
		for _, dn := range depNodes {
			if dn.in_edge() == me {
				s.generated_nodes_[dn] = true
				s.generator_rules_[me.rule_] = true
				ruleNames[me.rule_.Name] = true
				if s.delegate_ != nil {
					s.delegate_.OnMissingDep(node, dn.path_, me.rule_)
				}
			}
		}
	}
	s.missing_dep_path_count_ += len(ruleNames)
	s.nodes_missing_deps_[node] = true
}

// pathExistsBetween 判断从边 from 到边 to 是否存在路径（深度优先，带记忆化）。
func (s *MissingDependencyScanner) PathExistsBetween(from, to *Edge) bool {
	// 检查缓存
	if inner, ok := s.adjacency_map_[from]; ok {
		if val, ok := inner[to]; ok {
			return val
		}
	} else {
		s.adjacency_map_[from] = make(map[*Edge]bool)
	}
	found := false
	for _, in := range to.inputs_ {
		if e := in.in_edge(); e != nil {
			if e == from || s.PathExistsBetween(from, e) {
				found = true
				break
			}
		}
	}
	s.adjacency_map_[from][to] = found
	return found
}

// HadMissingDeps 返回是否检测到缺失依赖。
func (s *MissingDependencyScanner) HadMissingDeps() bool {
	return len(s.nodes_missing_deps_) > 0
}

// PrintStats 打印统计信息。
func (s *MissingDependencyScanner) PrintStats() {
	fmt.Printf("Processed %d nodes_.\n", len(s.seen_))
	if s.HadMissingDeps() {
		fmt.Printf("Error: There are %d missing dependency paths.\n", s.missing_dep_path_count_)
		fmt.Printf("%d targets_ had depfile dependencies on %d distinct generated inputs (from %d rules) without a non-depfile dep path to the generator.\n",
			len(s.nodes_missing_deps_), len(s.generated_nodes_), len(s.generator_rules_))
		fmt.Println("There might be build flakiness if any of the targets_ listed above are built alone, or not late enough, in a clean output directory.")
	} else {
		fmt.Println("No missing dependencies on generated files found.")
	}
}
