package builder

import (
	"fmt"
	"ninja-go/pkg/util"
	"strings"
)

// Delegate 接口，用于处理发现的缺失依赖。
type Delegate interface {
	OnMissingDep(node *Node, path string, rule *Rule)
}

// Printer 是一个简单的 Delegate 实现，打印缺失依赖信息。
type Printer struct{}

func NewPrinter() *Printer {
	return &Printer{}
}

func (p *Printer) OnMissingDep(node *Node, path string, rule *Rule) {
	fmt.Printf("Missing dep: %s uses %s (generated by %s)\n", node.Path, path, rule.Name)
}

// Scanner 扫描依赖日志，检测缺失依赖。
type Scanner struct {
	delegate            Delegate
	depsLog             *DepsLog
	state               *State
	disk                util.FileSystem
	seen                map[*Node]bool
	nodesMissingDeps    map[*Node]bool
	generatedNodes      map[*Node]bool
	generatorRules      map[*Rule]bool
	missingDepPathCount int
	adjacencyMap        map[*Edge]map[*Edge]bool
}

// NewScanner 创建 Scanner 实例。
func NewScanner(delegate Delegate, depsLog *DepsLog, state *State, disk util.FileSystem) *Scanner {
	return &Scanner{
		delegate:         delegate,
		depsLog:          depsLog,
		state:            state,
		disk:             disk,
		seen:             make(map[*Node]bool),
		nodesMissingDeps: make(map[*Node]bool),
		generatedNodes:   make(map[*Node]bool),
		generatorRules:   make(map[*Rule]bool),
		adjacencyMap:     make(map[*Edge]map[*Edge]bool),
	}
}

// ProcessNode 递归处理节点，收集其依赖并检测缺失。
func (s *Scanner) ProcessNode(node *Node) {
	if node == nil {
		return
	}
	edge := node.InEdge
	if edge == nil {
		return
	}
	if s.seen[node] {
		return
	}
	s.seen[node] = true

	// 递归处理输入节点
	for _, in := range edge.Inputs {
		s.ProcessNode(in)
	}

	// 获取依赖信息（从 deps log 或 depfile）
	depsType := edge.GetBinding("deps")
	if depsType != "" {
		deps := s.depsLog.GetDeps(node)
		if deps != nil {
			s.processNodeDeps(node, deps.nodes)
		}
	} else {
		// 从 depfile 加载依赖
		depfileNodes := s.loadDepfileDeps(edge)
		if len(depfileNodes) > 0 {
			s.processNodeDeps(node, depfileNodes)
		}
	}
}

// loadDepfileDeps 从 depfile 中读取依赖节点（不修改图的隐式依赖）。
func (s *Scanner) loadDepfileDeps(edge *Edge) []*Node {
	depfile := edge.GetUnescapedDepfile()
	if depfile == "" {
		return nil
	}
	// 展开 $out 等变量（简化：直接替换，实际应使用 edge.Env）
	depfile = strings.ReplaceAll(depfile, "$out", edge.Outputs[0].Path)
	var content string
	var err string
	status := s.disk.ReadFile(depfile, &content, &err)
	if status != util.StatusOkay {
		return nil
	}
	parser := NewDepfileParser(&DepfileParserOptions{})
	if !parser.Parse(content, &err) {
		return nil
	}
	var nodes []*Node
	for _, in := range parser.Ins {
		var slashBits uint64
		util.CanonicalizePathString(&in, &slashBits)
		node := s.state.GetNode(in, 0)
		nodes = append(nodes, node)
	}
	return nodes
}

// processNodeDeps 处理给定节点的依赖节点列表，检测是否有缺失路径。
func (s *Scanner) processNodeDeps(node *Node, depNodes []*Node) {
	edge := node.InEdge
	// 收集所有依赖边的集合
	depEdges := make(map[*Edge]bool)
	for _, dn := range depNodes {
		// 特殊例外：依赖 build.ninja 不算缺失（因为它由配置工具生成）
		if dn.Path == "build.ninja" {
			continue
		}
		if de := dn.InEdge; de != nil {
			depEdges[de] = true
		}
	}
	var missingEdges []*Edge
	for de := range depEdges {
		if !s.pathExistsBetween(de, edge) {
			missingEdges = append(missingEdges, de)
		}
	}
	if len(missingEdges) == 0 {
		return
	}
	// 记录缺失信息
	ruleNames := make(map[string]bool)
	for _, me := range missingEdges {
		for _, dn := range depNodes {
			if dn.InEdge == me {
				s.generatedNodes[dn] = true
				s.generatorRules[me.Rule] = true
				ruleNames[me.Rule.Name] = true
				if s.delegate != nil {
					s.delegate.OnMissingDep(node, dn.Path, me.Rule)
				}
			}
		}
	}
	s.missingDepPathCount += len(ruleNames)
	s.nodesMissingDeps[node] = true
}

// pathExistsBetween 判断从边 from 到边 to 是否存在路径（深度优先，带记忆化）。
func (s *Scanner) pathExistsBetween(from, to *Edge) bool {
	// 检查缓存
	if inner, ok := s.adjacencyMap[from]; ok {
		if val, ok := inner[to]; ok {
			return val
		}
	} else {
		s.adjacencyMap[from] = make(map[*Edge]bool)
	}
	found := false
	for _, in := range to.Inputs {
		if e := in.InEdge; e != nil {
			if e == from || s.pathExistsBetween(from, e) {
				found = true
				break
			}
		}
	}
	s.adjacencyMap[from][to] = found
	return found
}

// HadMissingDeps 返回是否检测到缺失依赖。
func (s *Scanner) HadMissingDeps() bool {
	return len(s.nodesMissingDeps) > 0
}

// PrintStats 打印统计信息。
func (s *Scanner) PrintStats() {
	fmt.Printf("Processed %d nodes.\n", len(s.seen))
	if s.HadMissingDeps() {
		fmt.Printf("Error: There are %d missing dependency paths.\n", s.missingDepPathCount)
		fmt.Printf("%d targets had depfile dependencies on %d distinct generated inputs (from %d rules) without a non-depfile dep path to the generator.\n",
			len(s.nodesMissingDeps), len(s.generatedNodes), len(s.generatorRules))
		fmt.Println("There might be build flakiness if any of the targets listed above are built alone, or not late enough, in a clean output directory.")
	} else {
		fmt.Println("No missing dependencies on generated files found.")
	}
}
